# Generated by Django 3.2.20 on 2023-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='your_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
