# Generated by Django 3.2.20 on 2023-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20230717_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
